# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spark-cli"
  version "0.3.2-202603051431"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.3.2-202603051431/spark-cli_darwin_amd64.tar.gz"
      sha256 "2bc20415bcc177d7efb721b237e5babdd83e7b7c898ddfe4b2c82e67c8f23eb3"

      define_method(:install) do
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.3.2-202603051431/spark-cli_darwin_arm64.tar.gz"
      sha256 "6ad32e65184204f31c376c0eaa63777e57aa29c5080a7fe9775ee4beb90e2056"

      define_method(:install) do
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.3.2-202603051431/spark-cli_linux_amd64.tar.gz"
      sha256 "831be5e12bce93ab2dcd3db9c640d0a9af1a158fe9d1c726ccab6fa560992ca2"
      define_method(:install) do
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.3.2-202603051431/spark-cli_linux_arm64.tar.gz"
      sha256 "b909f8517e3fe2ac806144dc3ffd581de6ad1d7d6f2fc79d9c4382d2c89d3dbf"
      define_method(:install) do
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
