# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spark-cli"
  version "0.2.13-202602210041"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.13-202602210041/spark-cli_darwin_amd64.tar.gz"
      sha256 "7ab116827e84d69ae487eba216fc276e4ceee29af774dbd3e8536a67351acf22"

      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.13-202602210041/spark-cli_darwin_arm64.tar.gz"
      sha256 "4a0d0c248bd9b66be7e280140c71877c52638c91c7f972bc891a717d6d7e9145"

      def install
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.13-202602210041/spark-cli_linux_amd64.tar.gz"
      sha256 "1fcb9fb28c5464fd11d66d2f8ee0cb08960bfca0997657fa222bcaaaebf54736"
      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.13-202602210041/spark-cli_linux_arm64.tar.gz"
      sha256 "979ddafbf82de554a91aedad44b17bbf166b087c92a1739bdad8fd3b998797b8"
      def install
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
