# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SparkCli < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spark-cli"
  version "0.2.9-202602202224"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.9-202602202224/spark-cli_darwin_amd64.tar.gz"
      sha256 "cb21fbc8de553c7474130e8792cbcc84d37881f2623107dd001c54994eda0862"

      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.9-202602202224/spark-cli_darwin_arm64.tar.gz"
      sha256 "eab7a9d0d624d1745af201d1e688aaf5bb2f3c76d58f4967e5a0a999014ad29f"

      def install
        bin.install "spark-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.9-202602202224/spark-cli_linux_amd64.tar.gz"
      sha256 "f69d343e7c81f51442f80d4e4698d8e0c26c480b1cbcd10a0ac535fc794ce50a"
      def install
        bin.install "spark-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spark-cli/releases/download/v0.2.9-202602202224/spark-cli_linux_arm64.tar.gz"
      sha256 "b2dcfae17893c750b6c8f780919c16812cf7edff5370d33e0d8144448838cacc"
      def install
        bin.install "spark-cli"
      end
    end
  end

  test do
    system "#{bin}/spark-cli", "version"
  end
end
