# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spk < Formula
  desc "Workspace CLI for multi-repo development"
  homepage "https://github.com/Spark-Rewards/homebrew-spk"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.7/spk_darwin_amd64.tar.gz"
      sha256 "fbe0f8eb385a72ec447ee54c5aa9847052b5a7815d1dd18bb4b6c86d1475c39a"

      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.7/spk_darwin_arm64.tar.gz"
      sha256 "a9d05e4ef07c0a6addbad6b0b9ef6618ed023274e5d1bb6802c7cd35fb5c43dc"

      def install
        bin.install "spk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.7/spk_linux_amd64.tar.gz"
      sha256 "d697d51f9d9635d49faf7d04771ed2422338df403bb71f9915b62631b61a0f1f"
      def install
        bin.install "spk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Spark-Rewards/homebrew-spk/releases/download/v0.1.7/spk_linux_arm64.tar.gz"
      sha256 "a530a8074282f527704b45d8bf82e7793277b5243bb3e72d276f402b75cbec3f"
      def install
        bin.install "spk"
      end
    end
  end

  test do
    system "#{bin}/spk", "version"
  end
end
